<a href="https://colab.research.google.com/github/AdewaleAkande/DATA-CLEANING-PROJECT/blob/main/COVID19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/covid_data.csv')

In [ ]:
data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18542 entries, 0 to 18541
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    18542 non-null  object
 1   continent                                   17038 non-null  object
 2   location                                    18542 non-null  object
 3   date                                        18541 non-null  object
 4   total_cases                                 18433 non-null  float64
 5   new_cases                                   18433 non-null  float64
 6   new_cases_smoothed                          18301 non-null  float64
 7   total_deaths                                17129 non-null  float64
 8   new_deaths                                  17151 non-null  float64
 9   new_deaths_smoothed                         17136 non-null  float64
 10  total_cases_per_million                     18433 non-null  float64
 11  new_cases_per_million                       18433 non-null  float64
 12  new_cases_smoothed_per_million              18301 non-null  float64
 13  total_deaths_per_million                    17129 non-null  float64
 14  new_deaths_per_million                      17151 non-null  float64
 15  new_deaths_smoothed_per_million             17136 non-null  float64
 16  reproduction_rate                           13582 non-null  float64
 17  icu_patients                                3208 non-null   float64
 18  icu_patients_per_million                    3208 non-null   float64
 19  hosp_patients                               2097 non-null   float64
 20  hosp_patients_per_million                   2097 non-null   float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      704 non-null    float64
 24  weekly_hosp_admissions_per_million          704 non-null    float64
 25  new_tests                                   6738 non-null   float64
 26  total_tests                                 7219 non-null   float64
 27  total_tests_per_thousand                    7219 non-null   float64
 28  new_tests_per_thousand                      6738 non-null   float64
 29  new_tests_smoothed                          8918 non-null   float64
 30  new_tests_smoothed_per_thousand             8918 non-null   float64
 31  positive_rate                               8577 non-null   float64
 32  tests_per_case                              8475 non-null   float64
 33  tests_units                                 9038 non-null   object
 34  total_vaccinations                          4547 non-null   float64
 35  people_vaccinated                           4489 non-null   float64
 36  people_fully_vaccinated                     4096 non-null   float64
 37  total_boosters                              1133 non-null   float64
 38  new_vaccinations                            3624 non-null   float64
 39  new_vaccinations_smoothed                   9430 non-null   float64
 40  total_vaccinations_per_hundred              4547 non-null   float64
 41  people_vaccinated_per_hundred               4489 non-null   float64
 42  people_fully_vaccinated_per_hundred         4096 non-null   float64
 43  total_boosters_per_hundred                  1133 non-null   float64
 44  new_vaccinations_smoothed_per_million       9430 non-null   float64
 45  new_people_vaccinated_smoothed              9408 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  9408 non-null   float64
 47  stringency_index                            14719 non-null  float64
 48  population                                  18541 non-null  float64
 49  population_density                          16340 non-null  float64
 50  median_age                                  14911 non-null  float64
 51  aged_65_older                               14911 non-null  float64
 52  aged_70_older                               14911 non-null  float64
 53  gdp_per_capita                              15617 non-null  float64
 54  extreme_poverty                             7753 non-null   float64
 55  cardiovasc_death_rate                       15628 non-null  float64
 56  diabetes_prevalence                         16340 non-null  float64
 57  female_smokers                              10982 non-null  float64
 58  male_smokers                                10982 non-null  float64
 59  handwashing_facilities                      7571 non-null   float64
 60  hospital_beds_per_thousand                  13494 non-null  float64
 61  life_expectancy                             17037 non-null  float64
 62  human_development_index                     14922 non-null  float64
 63  excess_mortality_cumulative_absolute        494 non-null    float64
 64  excess_mortality_cumulative                 494 non-null    float64
 65  excess_mortality                            494 non-null    float64
 66  excess_mortality_cumulative_per_million     494 non-null    float64
dtypes: float64(62), object(5)
memory usage: 9.5+ MB

In [ ]:
data['date'] = pd.to_datetime(data['date']) # To change the date format

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18542 entries, 0 to 18541
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    18542 non-null  object
 1   continent                                   17038 non-null  object
 2   location                                    18542 non-null  object
 3   date                                        18541 non-null  datetime64[ns]
 4   total_cases                                 18433 non-null  float64
 5   new_cases                                   18433 non-null  float64
 6   new_cases_smoothed                          18301 non-null  float64
 7   total_deaths                                17129 non-null  float64
 8   new_deaths                                  17151 non-null  float64
 9   new_deaths_smoothed                         17136 non-null  float64
 10  total_cases_per_million                     18433 non-null  float64
 11  new_cases_per_million                       18433 non-null  float64
 12  new_cases_smoothed_per_million              18301 non-null  float64
 13  total_deaths_per_million                    17129 non-null  float64
 14  new_deaths_per_million                      17151 non-null  float64
 15  new_deaths_smoothed_per_million             17136 non-null  float64
 16  reproduction_rate                           13582 non-null  float64
 17  icu_patients                                3208 non-null   float64
 18  icu_patients_per_million                    3208 non-null   float64
 19  hosp_patients                               2097 non-null   float64
 20  hosp_patients_per_million                   2097 non-null   float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      704 non-null    float64
 24  weekly_hosp_admissions_per_million          704 non-null    float64
 25  new_tests                                   6738 non-null   float64
 26  total_tests                                 7219 non-null   float64
 27  total_tests_per_thousand                    7219 non-null   float64
 28  new_tests_per_thousand                      6738 non-null   float64
 29  new_tests_smoothed                          8918 non-null   float64
 30  new_tests_smoothed_per_thousand             8918 non-null   float64
 31  positive_rate                               8577 non-null   float64
 32  tests_per_case                              8475 non-null   float64
 33  tests_units                                 9038 non-null   object
 34  total_vaccinations                          4547 non-null   float64
 35  people_vaccinated                           4489 non-null   float64
 36  people_fully_vaccinated                     4096 non-null   float64
 37  total_boosters                              1133 non-null   float64
 38  new_vaccinations                            3624 non-null   float64
 39  new_vaccinations_smoothed                   9430 non-null   float64
 40  total_vaccinations_per_hundred              4547 non-null   float64
 41  people_vaccinated_per_hundred               4489 non-null   float64
 42  people_fully_vaccinated_per_hundred         4096 non-null   float64
 43  total_boosters_per_hundred                  1133 non-null   float64
 44  new_vaccinations_smoothed_per_million       9430 non-null   float64
 45  new_people_vaccinated_smoothed              9408 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  9408 non-null   float64
 47  stringency_index                            14719 non-null  float64
 48  population                                  18541 non-null  float64
 49  population_density                          16340 non-null  float64
 50  median_age                                  14911 non-null  float64
 51  aged_65_older                               14911 non-null  float64
 52  aged_70_older                               14911 non-null  float64
 53  gdp_per_capita                              15617 non-null  float64
 54  extreme_poverty                             7753 non-null   float64
 55  cardiovasc_death_rate                       15628 non-null  float64
 56  diabetes_prevalence                         16340 non-null  float64
 57  female_smokers                              10982 non-null  float64
 58  male_smokers                                10982 non-null  float64
 59  handwashing_facilities                      7571 non-null   float64
 60  hospital_beds_per_thousand                  13494 non-null  float64
 61  life_expectancy                             17037 non-null  float64
 62  human_development_index                     14922 non-null  float64
 63  excess_mortality_cumulative_absolute        494 non-null    float64
 64  excess_mortality_cumulative                 494 non-null    float64
 65  excess_mortality                            494 non-null    float64
 66  excess_mortality_cumulative_per_million     494 non-null    float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 9.5+ MB

In [ ]:
data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [ ]:
data['iso_code'].unique()

array(['AFG', 'OWID_AFR', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ATG', 'ARG',
       'ARM', 'ABW', 'OWID_ASI', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD',
       'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL'],
      dtype=object)

In [ ]:
len(data['iso_code'])

163787

In [ ]:
data['location'].unique()  # number of iso_code = number of location.

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Asia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'European Union',
       'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'High income', 'Honduras', 'Hong Kong', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'International', 'Iran', 'Iraq',
       'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low income',
       'Lower middle income', 'Luxembourg', 'Macao', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Macedonia', 'Northern Cyprus', 'Norway',
       'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tokelau',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam', 'Wallis and Futuna',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
len(data['location']) # number of iso_code = number of location

163787

In [ ]:
data_Afghan= data.loc[data['location']== 'Afghanistan']

In [ ]:
data_Afghan.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 729
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    730 non-null    object
 1   continent                                   730 non-null    object
 2   location                                    730 non-null    object
 3   date                                        730 non-null    datetime64[ns]
 4   total_cases                                 730 non-null    float64
 5   new_cases                                   730 non-null    float64
 6   new_cases_smoothed                          725 non-null    float64
 7   total_deaths                                702 non-null    float64
 8   new_deaths                                  702 non-null    float64
 9   new_deaths_smoothed                         702 non-null    float64
 10  total_cases_per_million                     730 non-null    float64
 11  new_cases_per_million                       730 non-null    float64
 12  new_cases_smoothed_per_million              725 non-null    float64
 13  total_deaths_per_million                    702 non-null    float64
 14  new_deaths_per_million                      702 non-null    float64
 15  new_deaths_smoothed_per_million             702 non-null    float64
 16  reproduction_rate                           692 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  new_tests                                   0 non-null      float64
 26  total_tests                                 0 non-null      float64
 27  total_tests_per_thousand                    0 non-null      float64
 28  new_tests_per_thousand                      0 non-null      float64
 29  new_tests_smoothed                          0 non-null      float64
 30  new_tests_smoothed_per_thousand             0 non-null      float64
 31  positive_rate                               0 non-null      float64
 32  tests_per_case                              0 non-null      float64
 33  tests_units                                 0 non-null      object
 34  total_vaccinations                          42 non-null     float64
 35  people_vaccinated                           39 non-null     float64
 36  people_fully_vaccinated                     32 non-null     float64
 37  total_boosters                              0 non-null      float64
 38  new_vaccinations                            3 non-null      float64
 39  new_vaccinations_smoothed                   363 non-null    float64
 40  total_vaccinations_per_hundred              42 non-null     float64
 41  people_vaccinated_per_hundred               39 non-null     float64
 42  people_fully_vaccinated_per_hundred         32 non-null     float64
 43  total_boosters_per_hundred                  0 non-null      float64
 44  new_vaccinations_smoothed_per_million       363 non-null    float64
 45  new_people_vaccinated_smoothed              363 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  363 non-null    float64
 47  stringency_index                            708 non-null    float64
 48  population                                  730 non-null    float64
 49  population_density                          730 non-null    float64
 50  median_age                                  730 non-null    float64
 51  aged_65_older                               730 non-null    float64
 52  aged_70_older                               730 non-null    float64
 53  gdp_per_capita                              730 non-null    float64
 54  extreme_poverty                             0 non-null      float64
 55  cardiovasc_death_rate                       730 non-null    float64
 56  diabetes_prevalence                         730 non-null    float64
 57  female_smokers                              0 non-null      float64
 58  male_smokers                                0 non-null      float64
 59  handwashing_facilities                      730 non-null    float64
 60  hospital_beds_per_thousand                  730 non-null    float64
 61  life_expectancy                             730 non-null    float64
 62  human_development_index                     730 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 387.8+ KB

In [ ]:
data_Ghana= data.loc[data['location']== 'Ghana']

In [ ]:
data_Ghana.dropna(axis= 1, how='all')

Empty DataFrame
Columns: []
Index: []

In [ ]:
data_Ghana.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    0 non-null      object
 1   continent                                   0 non-null      object
 2   location                                    0 non-null      object
 3   date                                        0 non-null      datetime64[ns]
 4   total_cases                                 0 non-null      float64
 5   new_cases                                   0 non-null      float64
 6   new_cases_smoothed                          0 non-null      float64
 7   total_deaths                                0 non-null      float64
 8   new_deaths                                  0 non-null      float64
 9   new_deaths_smoothed                         0 non-null      float64
 10  total_cases_per_million                     0 non-null      float64
 11  new_cases_per_million                       0 non-null      float64
 12  new_cases_smoothed_per_million              0 non-null      float64
 13  total_deaths_per_million                    0 non-null      float64
 14  new_deaths_per_million                      0 non-null      float64
 15  new_deaths_smoothed_per_million             0 non-null      float64
 16  reproduction_rate                           0 non-null      float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  new_tests                                   0 non-null      float64
 26  total_tests                                 0 non-null      float64
 27  total_tests_per_thousand                    0 non-null      float64
 28  new_tests_per_thousand                      0 non-null      float64
 29  new_tests_smoothed                          0 non-null      float64
 30  new_tests_smoothed_per_thousand             0 non-null      float64
 31  positive_rate                               0 non-null      float64
 32  tests_per_case                              0 non-null      float64
 33  tests_units                                 0 non-null      object
 34  total_vaccinations                          0 non-null      float64
 35  people_vaccinated                           0 non-null      float64
 36  people_fully_vaccinated                     0 non-null      float64
 37  total_boosters                              0 non-null      float64
 38  new_vaccinations                            0 non-null      float64
 39  new_vaccinations_smoothed                   0 non-null      float64
 40  total_vaccinations_per_hundred              0 non-null      float64
 41  people_vaccinated_per_hundred               0 non-null      float64
 42  people_fully_vaccinated_per_hundred         0 non-null      float64
 43  total_boosters_per_hundred                  0 non-null      float64
 44  new_vaccinations_smoothed_per_million       0 non-null      float64
 45  new_people_vaccinated_smoothed              0 non-null      float64
 46  new_people_vaccinated_smoothed_per_hundred  0 non-null      float64
 47  stringency_index                            0 non-null      float64
 48  population                                  0 non-null      float64
 49  population_density                          0 non-null      float64
 50  median_age                                  0 non-null      float64
 51  aged_65_older                               0 non-null      float64
 52  aged_70_older                               0 non-null      float64
 53  gdp_per_capita                              0 non-null      float64
 54  extreme_poverty                             0 non-null      float64
 55  cardiovasc_death_rate                       0 non-null      float64
 56  diabetes_prevalence                         0 non-null      float64
 57  female_smokers                              0 non-null      float64
 58  male_smokers                                0 non-null      float64
 59  handwashing_facilities                      0 non-null      float64
 60  hospital_beds_per_thousand                  0 non-null      float64
 61  life_expectancy                             0 non-null      float64
 62  human_development_index                     0 non-null      float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 0.0+ bytes

In [ ]:
data_Ghana.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_Ghana['new_cases'].max()  # maximum new_cases

2521.0

In [ ]:
data_Ghana['new_cases'].min()    # minimum new_cases

0.0

In [ ]:
data_Ghana['total_deaths'].max()   # maximum total_dealth

1441.0

In [ ]:
data_Ghana['total_deaths'].min()    # minimum total_dealths

1.0

In [ ]:
data_Ghana_June.info()

<class 'pandas.core.series.Series'>
Int64Index: 711 entries, 57400 to 58110
Series name: date
Non-Null Count  Dtype
--------------  -----
711 non-null    bool
dtypes: bool(1)
memory usage: 6.2 KB

In [ ]:
data_Ghana_June.describe()

count       711
unique        1
top       False
freq        711
Name: date, dtype: object

In [ ]:
import seaborn as sns

In [ ]:
data_Ghana_June= data_Ghana[(data_Ghana['date'].dt.month== 6) & (data_Ghana['date'].dt.year== 2021)]

In [ ]:
data_Ghana.head()

Empty DataFrame
Columns: [iso_code, continent, location, date, total_cases, new_cases, new_cases_smoothed, total_deaths, new_deaths, new_deaths_smoothed, total_cases_per_million, new_cases_per_million, new_cases_smoothed_per_million, total_deaths_per_million, new_deaths_per_million, new_deaths_smoothed_per_million, reproduction_rate, icu_patients, icu_patients_per_million, hosp_patients, hosp_patients_per_million, weekly_icu_admissions, weekly_icu_admissions_per_million, weekly_hosp_admissions, weekly_hosp_admissions_per_million, new_tests, total_tests, total_tests_per_thousand, new_tests_per_thousand, new_tests_smoothed, new_tests_smoothed_per_thousand, positive_rate, tests_per_case, tests_units, total_vaccinations, people_vaccinated, people_fully_vaccinated, total_boosters, new_vaccinations, new_vaccinations_smoothed, total_vaccinations_per_hundred, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred, total_boosters_per_hundred, new_vaccinations_smoothed_per_million, new_people_vaccinated_smoothed, new_people_vaccinated_smoothed_per_hundred, stringency_index, population, population_density, median_age, aged_65_older, aged_70_older, gdp_per_capita, extreme_poverty, cardiovasc_death_rate, diabetes_prevalence, female_smokers, male_smokers, handwashing_facilities, hospital_beds_per_thousand, life_expectancy, human_development_index, excess_mortality_cumulative_absolute, excess_mortality_cumulative, excess_mortality, excess_mortality_cumulative_per_million]
Index: []

[0 rows x 67 columns]

In [ ]:
data_India= data.loc[data['location']== 'India']

In [ ]:
data_India.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 755 entries, 68623 to 69377
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    755 non-null    object
 1   continent                                   755 non-null    object
 2   location                                    755 non-null    object
 3   date                                        755 non-null    datetime64[ns]
 4   total_cases                                 755 non-null    float64
 5   new_cases                                   755 non-null    float64
 6   new_cases_smoothed                          750 non-null    float64
 7   total_deaths                                714 non-null    float64
 8   new_deaths                                  713 non-null    float64
 9   new_deaths_smoothed                         713 non-null    float64
 10  total_cases_per_million                     755 non-null    float64
 11  new_cases_per_million                       755 non-null    float64
 12  new_cases_smoothed_per_million              750 non-null    float64
 13  total_deaths_per_million                    714 non-null    float64
 14  new_deaths_per_million                      713 non-null    float64
 15  new_deaths_smoothed_per_million             713 non-null    float64
 16  reproduction_rate                           706 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  new_tests                                   680 non-null    float64
 26  total_tests                                 692 non-null    float64
 27  total_tests_per_thousand                    692 non-null    float64
 28  new_tests_per_thousand                      680 non-null    float64
 29  new_tests_smoothed                          703 non-null    float64
 30  new_tests_smoothed_per_thousand             703 non-null    float64
 31  positive_rate                               703 non-null    float64
 32  tests_per_case                              703 non-null    float64
 33  tests_units                                 710 non-null    object
 34  total_vaccinations                          393 non-null    float64
 35  people_vaccinated                           393 non-null    float64
 36  people_fully_vaccinated                     364 non-null    float64
 37  total_boosters                              40 non-null     float64
 38  new_vaccinations                            382 non-null    float64
 39  new_vaccinations_smoothed                   403 non-null    float64
 40  total_vaccinations_per_hundred              393 non-null    float64
 41  people_vaccinated_per_hundred               393 non-null    float64
 42  people_fully_vaccinated_per_hundred         364 non-null    float64
 43  total_boosters_per_hundred                  40 non-null     float64
 44  new_vaccinations_smoothed_per_million       403 non-null    float64
 45  new_people_vaccinated_smoothed              403 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  403 non-null    float64
 47  stringency_index                            740 non-null    float64
 48  population                                  755 non-null    float64
 49  population_density                          755 non-null    float64
 50  median_age                                  755 non-null    float64
 51  aged_65_older                               755 non-null    float64
 52  aged_70_older                               755 non-null    float64
 53  gdp_per_capita                              755 non-null    float64
 54  extreme_poverty                             755 non-null    float64
 55  cardiovasc_death_rate                       755 non-null    float64
 56  diabetes_prevalence                         755 non-null    float64
 57  female_smokers                              755 non-null    float64
 58  male_smokers                                755 non-null    float64
 59  handwashing_facilities                      755 non-null    float64
 60  hospital_beds_per_thousand                  755 non-null    float64
 61  life_expectancy                             755 non-null    float64
 62  human_development_index                     755 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 401.1+ KB

In [ ]:
data_India.dropna(axis= 1, how= 'all')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
68623,IND,Asia,India,2020-01-30,1.0,1.0,NaN,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
68624,IND,Asia,India,2020-01-31,1.0,0.0,NaN,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
68625,IND,Asia,India,2020-02-01,1.0,0.0,NaN,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
68626,IND,Asia,India,2020-02-02,2.0,1.0,NaN,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
68627,IND,Asia,India,2020-02-03,3.0,1.0,NaN,NaN,NaN,NaN,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69373,IND,Asia,India,2022-02-18,42802505.0,22270.0,30851.571,511230.0,325.0,464.143,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
69374,IND,Asia,India,2022-02-19,42822473.0,19968.0,27293.143,511903.0,673.0,462.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
69375,IND,Asia,India,2022-02-20,42838524.0,16051.0,24712.857,512109.0,206.0,442.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
69376,IND,Asia,India,2022-02-21,42851929.0,13405.0,22712.286,512344.0,235.0,426.571,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645
69377,IND,Asia,India,2022-02-22,42867031.0,15102.0,20496.143,512622.0,278.0,392.857,...,6426.674,21.2,282.28,10.39,1.9,20.6,59.55,0.53,69.66,0.645

In [ ]:
data_India.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 755 entries, 68623 to 69377
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    755 non-null    object
 1   continent                                   755 non-null    object
 2   location                                    755 non-null    object
 3   date                                        755 non-null    datetime64[ns]
 4   total_cases                                 755 non-null    float64
 5   new_cases                                   755 non-null    float64
 6   new_cases_smoothed                          750 non-null    float64
 7   total_deaths                                714 non-null    float64
 8   new_deaths                                  713 non-null    float64
 9   new_deaths_smoothed                         713 non-null    float64
 10  total_cases_per_million                     755 non-null    float64
 11  new_cases_per_million                       755 non-null    float64
 12  new_cases_smoothed_per_million              750 non-null    float64
 13  total_deaths_per_million                    714 non-null    float64
 14  new_deaths_per_million                      713 non-null    float64
 15  new_deaths_smoothed_per_million             713 non-null    float64
 16  reproduction_rate                           706 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  new_tests                                   680 non-null    float64
 26  total_tests                                 692 non-null    float64
 27  total_tests_per_thousand                    692 non-null    float64
 28  new_tests_per_thousand                      680 non-null    float64
 29  new_tests_smoothed                          703 non-null    float64
 30  new_tests_smoothed_per_thousand             703 non-null    float64
 31  positive_rate                               703 non-null    float64
 32  tests_per_case                              703 non-null    float64
 33  tests_units                                 710 non-null    object
 34  total_vaccinations                          393 non-null    float64
 35  people_vaccinated                           393 non-null    float64
 36  people_fully_vaccinated                     364 non-null    float64
 37  total_boosters                              40 non-null     float64
 38  new_vaccinations                            382 non-null    float64
 39  new_vaccinations_smoothed                   403 non-null    float64
 40  total_vaccinations_per_hundred              393 non-null    float64
 41  people_vaccinated_per_hundred               393 non-null    float64
 42  people_fully_vaccinated_per_hundred         364 non-null    float64
 43  total_boosters_per_hundred                  40 non-null     float64
 44  new_vaccinations_smoothed_per_million       403 non-null    float64
 45  new_people_vaccinated_smoothed              403 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  403 non-null    float64
 47  stringency_index                            740 non-null    float64
 48  population                                  755 non-null    float64
 49  population_density                          755 non-null    float64
 50  median_age                                  755 non-null    float64
 51  aged_65_older                               755 non-null    float64
 52  aged_70_older                               755 non-null    float64
 53  gdp_per_capita                              755 non-null    float64
 54  extreme_poverty                             755 non-null    float64
 55  cardiovasc_death_rate                       755 non-null    float64
 56  diabetes_prevalence                         755 non-null    float64
 57  female_smokers                              755 non-null    float64
 58  male_smokers                                755 non-null    float64
 59  handwashing_facilities                      755 non-null    float64
 60  hospital_beds_per_thousand                  755 non-null    float64
 61  life_expectancy                             755 non-null    float64
 62  human_development_index                     755 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 401.1+ KB

In [ ]:
data_India.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,7.550000e+02,755.000000,750.000000,714.000000,713.000000,713.000000,755.000000,755.000000,750.000000,714.000000,...,7.550000e+02,7.550000e+02,7.550000e+02,7.550000e+02,7.550000e+02,7.550000e+02,0.0,0.0,0.0,0.0
mean,1.642727e+07,56777.524503,57088.953141,230829.348739,708.622721,704.248663,11789.262842,40.747212,40.970691,165.658015,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN
std,1.436964e+07,82645.801147,82079.044883,181253.964135,902.647530,868.241512,10312.575070,59.311952,58.905214,130.079511,...,2.221918e-16,7.110138e-15,7.110138e-15,2.221918e-16,2.844055e-14,1.110959e-16,NaN,NaN,NaN,NaN
min,1.000000e+00,0.000000,0.000000,1.000000,-1.000000,0.143000,0.001000,0.000000,0.000000,0.001000,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN
25%,1.995805e+06,11006.500000,11460.999750,70880.000000,214.000000,242.429000,1432.318000,7.899000,8.225000,50.868250,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN
50%,1.087129e+07,29373.000000,30692.714000,157390.500000,435.000000,448.857000,7801.940000,21.080000,22.027000,112.953500,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN
75%,3.230406e+07,58672.000000,60190.535500,437715.000000,805.000000,838.143000,23183.471000,42.107000,43.196750,314.132500,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN
max,4.286703e+07,414188.000000,391232.000000,512622.000000,4529.000000,4190.000000,30764.140000,297.248000,280.773000,367.891000,...,1.900000e+00,2.060000e+01,5.955000e+01,5.300000e-01,6.966000e+01,6.450000e-01,NaN,NaN,NaN,NaN

In [ ]:
data_India['new_cases'].max()  # India maximum mew_cases

414188.0

In [ ]:
data_India['new_deaths'].max()

4529.0

In [ ]:
data_India['total_deaths'].max()  # maximun total_deaths in India

512622.0

In [ ]:
data_India['total_deaths'].min()  # minimum total_deaths in India

1.0

In [ ]:
data_India['new_cases'].min()

0.0

In [ ]:
data_S_Africa= data.loc[data['location']== 'South Africa']

In [ ]:
data_S_Africa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 747 entries, 135866 to 136612
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    747 non-null    object
 1   continent                                   747 non-null    object
 2   location                                    747 non-null    object
 3   date                                        747 non-null    datetime64[ns]
 4   total_cases                                 720 non-null    float64
 5   new_cases                                   719 non-null    float64
 6   new_cases_smoothed                          714 non-null    float64
 7   total_deaths                                698 non-null    float64
 8   new_deaths                                  697 non-null    float64
 9   new_deaths_smoothed                         697 non-null    float64
 10  total_cases_per_million                     720 non-null    float64
 11  new_cases_per_million                       719 non-null    float64
 12  new_cases_smoothed_per_million              714 non-null    float64
 13  total_deaths_per_million                    698 non-null    float64
 14  new_deaths_per_million                      697 non-null    float64
 15  new_deaths_smoothed_per_million             697 non-null    float64
 16  reproduction_rate                           702 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      93 non-null     float64
 24  weekly_hosp_admissions_per_million          93 non-null     float64
 25  new_tests                                   699 non-null    float64
 26  total_tests                                 714 non-null    float64
 27  total_tests_per_thousand                    714 non-null    float64
 28  new_tests_per_thousand                      699 non-null    float64
 29  new_tests_smoothed                          739 non-null    float64
 30  new_tests_smoothed_per_thousand             739 non-null    float64
 31  positive_rate                               712 non-null    float64
 32  tests_per_case                              712 non-null    float64
 33  tests_units                                 746 non-null    object
 34  total_vaccinations                          255 non-null    float64
 35  people_vaccinated                           246 non-null    float64
 36  people_fully_vaccinated                     200 non-null    float64
 37  total_boosters                              24 non-null     float64
 38  new_vaccinations                            181 non-null    float64
 39  new_vaccinations_smoothed                   369 non-null    float64
 40  total_vaccinations_per_hundred              255 non-null    float64
 41  people_vaccinated_per_hundred               246 non-null    float64
 42  people_fully_vaccinated_per_hundred         200 non-null    float64
 43  total_boosters_per_hundred                  24 non-null     float64
 44  new_vaccinations_smoothed_per_million       369 non-null    float64
 45  new_people_vaccinated_smoothed              369 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  369 non-null    float64
 47  stringency_index                            743 non-null    float64
 48  population                                  747 non-null    float64
 49  population_density                          747 non-null    float64
 50  median_age                                  747 non-null    float64
 51  aged_65_older                               747 non-null    float64
 52  aged_70_older                               747 non-null    float64
 53  gdp_per_capita                              747 non-null    float64
 54  extreme_poverty                             747 non-null    float64
 55  cardiovasc_death_rate                       747 non-null    float64
 56  diabetes_prevalence                         747 non-null    float64
 57  female_smokers                              747 non-null    float64
 58  male_smokers                                747 non-null    float64
 59  handwashing_facilities                      747 non-null    float64
 60  hospital_beds_per_thousand                  747 non-null    float64
 61  life_expectancy                             747 non-null    float64
 62  human_development_index                     747 non-null    float64
 63  excess_mortality_cumulative_absolute        106 non-null    float64
 64  excess_mortality_cumulative                 106 non-null    float64
 65  excess_mortality                            106 non-null    float64
 66  excess_mortality_cumulative_per_million     106 non-null    float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 396.8+ KB

In [ ]:
data_S_Africa.dropna(axis= 1, how= 'all')

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
135866,ZAF,Africa,South Africa,2020-02-07,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
135867,ZAF,Africa,South Africa,2020-02-08,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
135868,ZAF,Africa,South Africa,2020-02-09,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,33.2,43.993,2.32,64.13,0.709,1579.2,2.82,8.13,26.301591
135869,ZAF,Africa,South Africa,2020-02-10,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
135870,ZAF,Africa,South Africa,2020-02-11,NaN,NaN,NaN,NaN,NaN,NaN,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136608,ZAF,Africa,South Africa,2022-02-18,3654824.0,2800.0,2450.143,98298.0,343.0,206.714,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
136609,ZAF,Africa,South Africa,2022-02-19,3657091.0,2267.0,2418.429,98617.0,319.0,233.143,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
136610,ZAF,Africa,South Africa,2022-02-20,3658547.0,1456.0,2390.857,98667.0,50.0,239.143,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
136611,ZAF,Africa,South Africa,2022-02-21,3659698.0,1151.0,2399.000,98804.0,137.0,222.000,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN
136612,ZAF,Africa,South Africa,2022-02-22,3662032.0,2334.0,2394.714,98868.0,64.0,205.286,...,8.1,33.2,43.993,2.32,64.13,0.709,NaN,NaN,NaN,NaN

In [ ]:
data_S_Africa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 747 entries, 135866 to 136612
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    747 non-null    object
 1   continent                                   747 non-null    object
 2   location                                    747 non-null    object
 3   date                                        747 non-null    datetime64[ns]
 4   total_cases                                 720 non-null    float64
 5   new_cases                                   719 non-null    float64
 6   new_cases_smoothed                          714 non-null    float64
 7   total_deaths                                698 non-null    float64
 8   new_deaths                                  697 non-null    float64
 9   new_deaths_smoothed                         697 non-null    float64
 10  total_cases_per_million                     720 non-null    float64
 11  new_cases_per_million                       719 non-null    float64
 12  new_cases_smoothed_per_million              714 non-null    float64
 13  total_deaths_per_million                    698 non-null    float64
 14  new_deaths_per_million                      697 non-null    float64
 15  new_deaths_smoothed_per_million             697 non-null    float64
 16  reproduction_rate                           702 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      93 non-null     float64
 24  weekly_hosp_admissions_per_million          93 non-null     float64
 25  new_tests                                   699 non-null    float64
 26  total_tests                                 714 non-null    float64
 27  total_tests_per_thousand                    714 non-null    float64
 28  new_tests_per_thousand                      699 non-null    float64
 29  new_tests_smoothed                          739 non-null    float64
 30  new_tests_smoothed_per_thousand             739 non-null    float64
 31  positive_rate                               712 non-null    float64
 32  tests_per_case                              712 non-null    float64
 33  tests_units                                 746 non-null    object
 34  total_vaccinations                          255 non-null    float64
 35  people_vaccinated                           246 non-null    float64
 36  people_fully_vaccinated                     200 non-null    float64
 37  total_boosters                              24 non-null     float64
 38  new_vaccinations                            181 non-null    float64
 39  new_vaccinations_smoothed                   369 non-null    float64
 40  total_vaccinations_per_hundred              255 non-null    float64
 41  people_vaccinated_per_hundred               246 non-null    float64
 42  people_fully_vaccinated_per_hundred         200 non-null    float64
 43  total_boosters_per_hundred                  24 non-null     float64
 44  new_vaccinations_smoothed_per_million       369 non-null    float64
 45  new_people_vaccinated_smoothed              369 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  369 non-null    float64
 47  stringency_index                            743 non-null    float64
 48  population                                  747 non-null    float64
 49  population_density                          747 non-null    float64
 50  median_age                                  747 non-null    float64
 51  aged_65_older                               747 non-null    float64
 52  aged_70_older                               747 non-null    float64
 53  gdp_per_capita                              747 non-null    float64
 54  extreme_poverty                             747 non-null    float64
 55  cardiovasc_death_rate                       747 non-null    float64
 56  diabetes_prevalence                         747 non-null    float64
 57  female_smokers                              747 non-null    float64
 58  male_smokers                                747 non-null    float64
 59  handwashing_facilities                      747 non-null    float64
 60  hospital_beds_per_thousand                  747 non-null    float64
 61  life_expectancy                             747 non-null    float64
 62  human_development_index                     747 non-null    float64
 63  excess_mortality_cumulative_absolute        106 non-null    float64
 64  excess_mortality_cumulative                 106 non-null    float64
 65  excess_mortality                            106 non-null    float64
 66  excess_mortality_cumulative_per_million     106 non-null    float64
dtypes: datetime64[ns](1), float64(62), object(4)
memory usage: 396.8+ KB

In [ ]:
data_S_Africa.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,7.200000e+02,719.000000,714.000000,698.000000,697.000000,697.000000,720.000000,719.000000,714.000000,698.000000,...,7.470000e+02,7.470000e+02,747.000,747.00,747.00,7.470000e+02,106.000000,106.000000,106.000000,106.000000
mean,1.539366e+06,5067.379694,5093.886952,46398.157593,141.057389,140.268911,25638.153275,84.397253,84.838744,772.761723,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,105609.289623,13.362830,23.647358,1758.923698
std,1.155933e+06,5686.316856,5344.095164,33402.214429,147.440401,128.737231,19252.078419,94.705650,89.005955,556.314176,...,1.777547e-15,7.110188e-15,0.000,0.00,0.00,2.221934e-16,93333.763001,9.665619,31.639108,1554.474688
min,1.000000e+00,0.000000,1.000000,1.000000,-228.000000,0.143000,0.017000,0.000000,0.017000,0.017000,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,-8630.200000,-3.710000,-16.680000,-143.736061
25%,6.279545e+05,1050.500000,1205.356750,15793.250000,43.000000,53.571000,10458.587750,17.496000,20.075000,263.036750,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,20732.875000,6.327500,6.497500,345.306225
50%,1.512809e+06,2488.000000,2621.714000,51062.500000,93.000000,91.143000,25195.847500,41.438000,43.664500,850.446500,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,114821.250000,19.090000,14.410000,1912.348983
75%,2.737984e+06,8049.000000,8485.428250,82437.250000,184.000000,192.000000,45601.153250,134.056000,141.324750,1372.993500,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,203548.325000,23.212500,30.722500,3390.099240
max,3.662032e+06,37875.000000,23437.143000,98868.000000,844.000000,577.571000,60991.177000,630.808000,390.346000,1646.647000,...,8.100000e+00,3.320000e+01,43.993,2.32,64.13,7.090000e-01,254684.700000,24.790000,170.680000,4241.776040

In [ ]:
data_S_Africa['new_cases'].max()   # maximum new_cases in South Africa

37875.0

In [ ]:
data_S_Africa['new_deaths'].max()  # maximum new_deaths in South Africa

844.0

In [ ]:
data_S_Africa['total_deaths'].max()   # maximum total_deaths in South Africa

98868.0